// This file is generated by kconfig_compiler from kdvi.kcfg.
// All changes you do to this file will be lost.

#include "prefs.h"

#include <fontpool.h>
#include <kstaticdeleter.h>

Prefs *Prefs::mSelf = 0;
static KStaticDeleter<Prefs> staticPrefsDeleter;

Prefs *Prefs::self()
{
  if ( !mSelf ) {
    staticPrefsDeleter.setObject( mSelf, new Prefs() );
    mSelf->readConfig();
  }

  return mSelf;
}

Prefs::Prefs(  )
  : KConfigSkeleton( QString::fromLatin1( "kdvirc" ) )
{
  mSelf = this;
  setCurrentGroup( QString::fromLatin1( "kdvi" ) );

  KConfigSkeleton::ItemInt  *itemMetafontMode;
  itemMetafontMode = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "MetafontMode" ), mMetafontMode, DefaultMFMode );
  itemMetafontMode->setMinValue(0);
  itemMetafontMode->setMaxValue(NumberOfMFModes-1);
  addItem( itemMetafontMode, QString::fromLatin1( "MetafontMode" ) );
  KConfigSkeleton::ItemBool  *itemMakePK;
  itemMakePK = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "MakePK" ), mMakePK, true );
  addItem( itemMakePK, QString::fromLatin1( "MakePK" ) );
  KConfigSkeleton::ItemBool  *itemShowPS;
  itemShowPS = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "ShowPS" ), mShowPS, true );
  addItem( itemShowPS, QString::fromLatin1( "ShowPS" ) );
  KConfigSkeleton::ItemBool  *itemShowHyperLinks;
  itemShowHyperLinks = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "ShowHyperLinks" ), mShowHyperLinks, true );
  addItem( itemShowHyperLinks, QString::fromLatin1( "ShowHyperLinks" ) );
  KConfigSkeleton::ItemBool  *itemUseType1Fonts;
  itemUseType1Fonts = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "UseType1Fonts" ), mUseType1Fonts, true );
  addItem( itemUseType1Fonts, QString::fromLatin1( "UseType1Fonts" ) );
  KConfigSkeleton::ItemBool  *itemUseFontHints;
  itemUseFontHints = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "UseFontHints" ), mUseFontHints, false );
  addItem( itemUseFontHints, QString::fromLatin1( "UseFontHints" ) );
  QValueList<KConfigSkeleton::ItemEnum::Choice> valuesViewMode;
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "KVS_SingePage" );
    valuesViewMode.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "KVS_Continuous" );
    valuesViewMode.append( choice );
  }
  {
    KConfigSkeleton::ItemEnum::Choice choice;
    choice.name = QString::fromLatin1( "KVS_ContinuousFacing" );
    valuesViewMode.append( choice );
  }
  KConfigSkeleton::ItemEnum  *itemViewMode;
  itemViewMode = new KConfigSkeleton::ItemEnum( currentGroup(), QString::fromLatin1( "ViewMode" ), mViewMode, valuesViewMode, EnumViewMode::KVS_Continuous );
  addItem( itemViewMode, QString::fromLatin1( "ViewMode" ) );
  KConfigSkeleton::ItemPath  *itemEditorCommand;
  itemEditorCommand = new KConfigSkeleton::ItemPath( currentGroup(), QString::fromLatin1( "EditorCommand" ), mEditorCommand );
  addItem( itemEditorCommand, QString::fromLatin1( "EditorCommand" ) );
}

Prefs::~Prefs()
{
  if ( mSelf == this )
    staticPrefsDeleter.setObject( mSelf, 0, false );
}

