/**********************************************************************

	--- Dlgedit generated file ---

	File: printData.h
	Last generated: Fri Oct 3 00:46:41 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#ifndef printData_included
#define printData_included

#include <qdialog.h>
#include <qchkbox.h>
#include <qcombo.h>
#include <qlabel.h>
#include <qlined.h>
#include <qpushbt.h>
#include <qradiobt.h>

class printData : public QDialog
{
    Q_OBJECT

public:

    printData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~printData();

public slots:


protected slots:

    virtual void cancelPressed();
    virtual void rangeToggled(bool);
    virtual void printDestinationChanged(int);
    virtual void setupPressed();
    virtual void okPressed();
    virtual void nupPressed(int);

protected:
    QLabel* fileNameLabel;
    QComboBox* printer;
    QLineEdit* printFileName;
    QRadioButton* printAll;
    QRadioButton* printCurrent;
    QRadioButton* printMarked;
    QRadioButton* printRange;
    QLineEdit* rangeFrom;
    QLineEdit* rangeTo;
    QCheckBox* printReverse;
    QComboBox* nupCombo;
    QComboBox* colOrder;
    QPushButton* okButton;
    QPushButton* setupButton;
    QPushButton* cancelButton;

};

#endif // printData_included
