/**********************************************************************

	--- Dlgedit generated file ---

	File: printSetupData.h
	Last generated: Sun Oct 12 22:01:03 1997

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#ifndef printSetupData_included
#define printSetupData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qlined.h>
#include <qlistbox.h>
#include <qpushbt.h>
#include <qradiobt.h>

class printSetupData : public QDialog
{
    Q_OBJECT

public:

    printSetupData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~printSetupData();

public slots:


protected slots:

    virtual void removePrinter();
    virtual void okPressed();
    virtual void addPrinter();

protected:
    QRadioButton* internal;
    QRadioButton* dvips;
    QRadioButton* dvilj4;
    QRadioButton* psnup;
    QRadioButton* mpage;
    QListBox* printers;
    QLineEdit* newPrinter;
    QPushButton* okButton;
    QLineEdit* spoolerCommand;
    QLabel* spoolerLabel;

};

#endif // printSetupData_included
